name = "righelt-api"
main = "src/index.ts"
compatibility_date = "2026-02-23"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "righelt-db-dev"
database_id = "22435cc4-6655-4bdf-a05d-d100cd8e6cc9"

