import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = fileURLToPath(new URL(".", import.meta.url));
const source = readFileSync(join(testDir, "..", "shell", "app.js"), "utf8");

test("shell render patches same-route game updates without replacing the board panel", () => {
  assert.match(source, /FLYOUT_KEYS,/);
  assert.match(source, /let lastRenderedMarkup = "";/);
  assert.match(source, /let stickyLayoutFrame = 0;/);
  assert.match(source, /const SHELL_WIDE_SCREEN_MIN_WIDTH = 901;/);
  assert.match(source, /const FLYOUT_MOTION_MS = 180;/);
  assert.match(source, /appEl\.setAttribute\("data-shell-layout-mode", "narrow"\);/);
  assert.match(source, /const renderGameShellFrame = \(game\) =>/);
  assert.match(source, /const renderScenarioFlyout = \(\) =>/);
  assert.match(source, /const renderDebugFlyout = \(\) =>/);
  assert.match(source, /<section class="panel debug-panel scenario-panel scenario-panel-load">/);
  assert.match(source, /<section class="panel debug-panel scenario-panel scenario-panel-create">/);
  assert.match(source, /const renderFlyout = \(\{ title, variant, closeAction, body \}\) =>/);
  assert.match(source, /class="shell-flyout-scroll shell-flyout-scroll-\$\{variant\}"/);
  assert.match(source, /closeAction:\s*"close-debug"/);
  assert.match(source, /closeAction:\s*"close-scenarios"/);
  assert.match(source, /class="secondary\$\{currentRoute\.scenarios \? " is-active" : ""\}"/);
  assert.match(source, /data-action="\$\{currentRoute\.scenarios \? "close-scenarios" : "open-scenarios"\}"/);
  assert.match(source, /aria-pressed="\$\{currentRoute\.scenarios \? "true" : "false"\}"/);
  assert.match(source, /class="secondary\$\{currentRoute\.debug \? " is-active" : ""\}"/);
  assert.match(source, /data-action="\$\{currentRoute\.debug \? "close-debug" : "open-debug"\}"/);
  assert.match(source, /aria-pressed="\$\{currentRoute\.debug \? "true" : "false"\}"/);
  assert.match(source, /title: "Debug mode"/);
  assert.match(source, /Scenarios/);
  assert.match(source, /const renderDebugContent = \(\) => \{[\s\S]*?<h2>Engine Status<\/h2>[\s\S]*?<h2>Actions Diagnostics<\/h2>/s);
  assert.match(source, /id="shell-game-alerts"/);
  assert.match(source, /data-game-shell-root data-game-id=/);
  assert.match(source, /data-shell-sticky-target="left" data-sticky-enabled="false"/);
  assert.match(source, /data-shell-sticky-target="board" data-sticky-enabled="false"/);
  assert.match(source, /data-game-panel="history"/);
  assert.match(source, /const updateMountedGameShell = \(\{ game, inviteFromRole = null, inviteToken = null, includeBoard = true \} = \{\}\) => \{/);
  assert.match(source, /const getMountedHeaderEl = \(\) =>/);
  assert.match(source, /const updateMountedHeader = \(\) => \{/);
  assert.match(source, /currentHeaderEl\.replaceWith\(nextHeaderEl\);/);
  assert.match(source, /const doesMountedFlyoutStateMatchRoute = \(\) => \{/);
  assert.match(source, /return FLYOUT_KEYS\.every\(\(flyoutKey\) => \{/);
  assert.match(source, /const shouldEnableStickyShellColumn = \(\{ matchesWideScreen, columnHeight, viewportHeight \}\) =>/);
  assert.match(source, /const getCurrentFlyoutState = \(\) => \(\{\s*\.\.\.Object\.fromEntries\(FLYOUT_KEYS\.map\(\(key\) => \[key, currentRoute\[key\] === true\]\)\),\s*\}\);/s);
  assert.match(source, /const getBaseRouteRenderKey = \(route = currentRoute\) => \{/);
  assert.match(source, /const getRouteRenderKey = \(route = currentRoute\) =>/);
  assert.match(source, /const isFlyoutOnlyRouteChange = \(previousRoute, nextRoute\) =>/);
  assert.match(source, /let flyoutRenderOrder = FLYOUT_KEYS\.filter\(\(key\) => currentRoute\[key\] === true\);/);
  assert.match(source, /const syncFlyoutRenderOrder = \(route = currentRoute\) => \{/);
  assert.match(source, /const setFlyoutOpenState = \(key, isOpen\) => \{/);
  assert.match(source, /const getOpenFlyoutCount = \(route = currentRoute\) => FLYOUT_KEYS\.reduce\(\(count, key\) => count \+ Number\(route\?\.\[key\] === true\), 0\);/);
  assert.match(source, /const getWideFlyoutWidth = \(viewportWidth = window\.innerWidth\) => \{/);
  assert.match(source, /const getAvailableShellContentWidth = \(viewportWidth = window\.innerWidth, route = currentRoute\) => \{/);
  assert.match(source, /const SHELL_VIEWPORT_GUTTER_PX = 16;/);
  assert.match(source, /const totalHorizontalGutter = SHELL_VIEWPORT_GUTTER_PX \* 2;/);
  assert.match(source, /return Math\.max\(0, viewportWidth - totalHorizontalGutter\);/);
  assert.match(source, /return Math\.max\(0, viewportWidth - \(getWideFlyoutWidth\(viewportWidth\) \* openFlyoutCount\) - totalHorizontalGutter\);/);
  assert.match(source, /const getShellLayoutModeForRoute = \(route = currentRoute, viewportWidth = window\.innerWidth\) =>/);
  assert.match(source, /getAvailableShellContentWidth\(viewportWidth, route\) >= SHELL_WIDE_SCREEN_MIN_WIDTH \? "wide" : "narrow"/);
  assert.match(source, /const getShellLayoutMode = \(viewportWidth = window\.innerWidth\) => getShellLayoutModeForRoute\(currentRoute, viewportWidth\);/);
  assert.match(source, /const scrollHomeSectionToTop = \(sectionKey\) => \{/);
  assert.match(source, /window\.requestAnimationFrame\(\(\) => \{\s*scrollHomeSectionToTop\(sectionKey\);\s*\}\);/s);
  assert.match(source, /const syncShellLayoutMode = \(\) => \{/);
  assert.match(source, /appEl\.setAttribute\("data-shell-layout-mode", layoutMode\);/);
  assert.match(source, /FLYOUT_KEYS\.forEach\(\(key\) => \{\s*appEl\.setAttribute\(`data-\$\{key\}-open`, currentRoute\[key\] \? "true" : "false"\);\s*\}\);/s);
  assert.match(source, /appEl\.setAttribute\("data-flyout-count", String\(getOpenFlyoutCount\(\)\)\);/);
  assert.match(source, /appEl\.setAttribute\("data-shell-content-width", String\(Math\.round\(getAvailableShellContentWidth\(\)\)\)\);/);
  assert.match(source, /const applyGameShellStickyLayout = \(\) => \{/);
  assert.match(source, /const scheduleGameShellStickyLayout = \(\) => \{/);
  assert.match(source, /window\.cancelAnimationFrame\(stickyLayoutFrame\);/);
  assert.match(source, /stickyLayoutFrame = window\.requestAnimationFrame\(\(\) => \{\s*stickyLayoutFrame = 0;\s*applyGameShellStickyLayout\(\);\s*\}\);/s);
  assert.match(source, /const layoutMode = syncShellLayoutMode\(\);/);
  assert.match(source, /const matchesWideScreen = layoutMode === "wide";/);
  assert.match(source, /const columnHeight = Math\.round\(targetEl\.getBoundingClientRect\(\)\.height\);/);
  assert.match(source, /targetEl\.setAttribute\("data-sticky-enabled", stickyEnabled \? "true" : "false"\);/);
  assert.match(source, /const mountedGameShell = getMountedGameShellRoot\(\);/);
  assert.match(source, /shouldUseIncrementalGameShell\(\)/);
  assert.match(source, /updateMountedGameShell\(\{\s*game: transport\.getGameViewModel\(currentRoute\.gameId\),/s);
  assert.match(source, /includeBoard: change\?\.type !== "optimistic_enqueue"/);
  assert.match(source, /const getAnimatedPanels = \(\) =>/);
  assert.match(source, /const getAnimatedFlyoutEls = \(layoutMode = getShellLayoutMode\(\)\) => \{/);
  assert.match(source, /const mainContentEl = layoutMode === "wide" \? appEl\.querySelector\("\.shell-main-content"\) : null;/);
  assert.match(source, /const getAnimatedFlyoutKey = \(element\) => \{/);
  assert.match(source, /const getCssPixelValue = \(value, fallback = 0\) => \{/);
  assert.match(source, /const getFlyoutContentGapPx = \(\) =>/);
  assert.match(source, /const getShellMainMaxWidthPx = \(\) =>/);
  assert.match(source, /const getWideShellPaddingRightPx = \(openFlyoutCount, viewportWidth = window\.innerWidth\) => \{/);
  assert.match(source, /const getWideMainContentWidthPx = \(openFlyoutCount, viewportWidth = window\.innerWidth\) => \{/);
  assert.match(source, /const captureFlyoutRects = \(layoutMode = getShellLayoutMode\(\)\) =>/);
  assert.match(source, /const animateFlyoutShift = \(element, \{ deltaX = 0, deltaY = 0, fromOpacity = 1, fromWidth = null, toWidth = null \} = \{\}\) => \{/);
  assert.match(source, /const animateFlyoutPositionChanges = \(previousRects\) => \{/);
  assert.doesNotMatch(source, /previousRects\.size === 0/);
  assert.match(source, /const clearCoordinatedFlyoutMotionStyles = \(\) => \{/);
  assert.match(source, /const hasWidthChange = Number\.isFinite\(fromWidth\) && Number\.isFinite\(toWidth\) && Math\.abs\(toWidth - fromWidth\) >= 1;/);
  assert.match(source, /element\.style\.width = `\$\{fromWidth\}px`;/);
  assert.match(source, /element\.style\.maxWidth = `\$\{fromWidth\}px`;/);
  assert.match(source, /element\.style\.transition = `transform \$\{FLYOUT_MOTION_MS\}ms ease, opacity \$\{FLYOUT_MOTION_MS\}ms ease, width \$\{FLYOUT_MOTION_MS\}ms ease, max-width \$\{FLYOUT_MOTION_MS\}ms ease`;/);
  assert.match(source, /element\.style\.width = `\$\{toWidth\}px`;/);
  assert.match(source, /element\.style\.maxWidth = `\$\{toWidth\}px`;/);
  assert.match(source, /const capturePanelHeights = \(\) =>/);
  assert.match(source, /const shouldPatchFlyoutsOnly = shouldPatchMountedFlyouts\(routeKey, baseRouteKey\);/);
  assert.match(source, /const previousPanelHeights = animatePanels && !shouldPatchFlyoutsOnly \? capturePanelHeights\(\) : \[\];/);
  assert.match(source, /const previousFlyoutRects = animatePanels \? captureFlyoutRects\(\) : new Map\(\);/);
  assert.match(source, /const animatePanelHeightChange = \(panelEl, fromHeight\) => \{/);
  assert.match(source, /const animatePanelHeightChanges = \(previousPanelHeights\) => \{/);
  assert.match(source, /const getMountedShellPageEl = \(\) =>/);
  assert.match(source, /const getFlyoutAwareHref = \(element\) => \{/);
  assert.match(source, /const syncFlyoutAwareLinks = \(\) => \{/);
  assert.match(source, /const syncCopyInviteLinks = \(\) => \{/);
  assert.match(source, /const updateMountedFlyouts = \(\) => \{/);
  assert.match(source, /const shouldPatchMountedFlyouts = \(routeKey = getRouteRenderKey\(\), baseRouteKey = getBaseRouteRenderKey\(\)\) =>/);
  assert.match(source, /const syncRenderedMarkupSnapshot = \(\) => \{/);
  assert.match(source, /const FLYOUT_RENDERERS = \{/);
  assert.match(source, /const renderFlyoutBodyByKey = \(flyoutKey\) => \{/);
  assert.match(source, /scenarios:\s*\(\) => renderScenarioFlyout\(\)/);
  assert.match(source, /debug:\s*\(\) => renderDebugFlyout\(\)/);
  assert.match(source, /fromWidth: previousRect\.width,/);
  assert.match(source, /toWidth: nextRect\.width,/);
  assert.match(source, /getAnimatedFlyoutEls\(layoutMode\)\.forEach\(\(element\) => \{/);
  assert.match(source, /deltaX: layoutMode === "wide" \? nextRect\.width : 0,/);
  assert.match(source, /deltaY: layoutMode === "wide" \? 0 : nextRect\.height,/);
  assert.match(source, /querySelectorAll\("\.panel"\)/);
  assert.match(source, /class="panel" data-shell-panel="board"/);
  assert.match(source, /scheduleGameShellStickyLayout\(\);/);
  assert.match(source, /window\.addEventListener\("resize", \(\) => \{\s*scheduleGameShellStickyLayout\(\);\s*\}\);/s);
  assert.match(source, /window\.addEventListener\("load", \(\) => \{\s*scheduleGameShellStickyLayout\(\);\s*\}\);/s);
  assert.match(source, /syncFlyoutRenderOrder\(currentRoute\);/);
  assert.match(source, /if \(isFlyoutOnlyRouteChange\(previousRoute, nextRoute\)\) \{[\s\S]*render\(\);\s*return;\s*\}/s);
  assert.match(source, /if \(isFlyoutOnlyRouteChange\(previousRoute, currentRoute\)\) \{[\s\S]*render\(\);\s*return;\s*\}/s);
  assert.match(source, /setFlyoutOpenState\("debug", true\);/);
  assert.match(source, /setFlyoutOpenState\("scenarios", true\);/);
  assert.match(source, /const animateFlyoutClose = async \(flyoutKey, closeFlyout\) => \{/);
  assert.match(source, /const mainContentEl = appEl\?\.querySelector\?\.\("\.shell-main-content"\);/);
  assert.match(source, /const layoutMode = getShellLayoutMode\(\);/);
  assert.match(source, /if \(layoutMode === "wide"\) \{/);
  assert.match(source, /const nextFlyoutCount = Math\.max\(0, getOpenFlyoutCount\(\) - 1\);/);
  assert.match(source, /const currentAppPaddingRight = window\.getComputedStyle\(appEl\)\.paddingRight;/);
  assert.match(source, /const nextAppPaddingRight = getWideShellPaddingRightPx\(nextFlyoutCount\);/);
  assert.match(source, /appEl\.style\.transition = `padding-right \$\{FLYOUT_MOTION_MS\}ms ease`;/);
  assert.match(source, /const nextMainWidth = getWideMainContentWidthPx\(nextFlyoutCount\);/);
  assert.match(source, /mainContentEl\.style\.transition = `width \$\{FLYOUT_MOTION_MS\}ms ease, max-width \$\{FLYOUT_MOTION_MS\}ms ease`;/);
  assert.match(source, /flyoutEl\.classList\.add\("is-closing"\);/);
  assert.match(source, /await delay\(FLYOUT_MOTION_MS\);/);
  assert.match(source, /clearCoordinatedFlyoutMotionStyles\(\);/);
  assert.match(source, /const nextMarkup = `<div class="shell-page-shell"><div class="shell-main-content">\$\{renderHeader\(\)\}\$\{body\}<\/div>\$\{renderFlyouts\(\)\}<\/div>`;/);
  assert.match(source, /if \(shouldPatchFlyoutsOnly\) \{\s*updateMountedHeader\(\);\s*updateMountedFlyouts\(\);\s*syncFlyoutAwareLinks\(\);\s*syncCopyInviteLinks\(\);\s*updateHeaderFields\(\);\s*reconcileMiniBoardPreviews\(\);[\s\S]*syncRenderedMarkupSnapshot\(\);\s*return;\s*\}/s);
  assert.match(source, /shouldUseIncrementalGameShell\(\) &&[\s\S]*updateMountedHeader\(\);\s*updateHeaderFields\(\);\s*syncScenarioAuthoringControls\(\);\s*updateMountedGameShell\(/s);
  assert.match(source, /if \(nextMarkup !== lastRenderedMarkup\) \{\s*appEl\.innerHTML = nextMarkup;\s*lastRenderedMarkup = nextMarkup;[\s\S]*lastRenderedRouteKey = routeKey;[\s\S]*if \(animatePanels\) \{\s*animatePanelHeightChanges\(previousPanelHeights\);\s*animateFlyoutPositionChanges\(previousFlyoutRects\);\s*\}\s*\}/s);
  assert.equal((source.match(/appEl\.innerHTML\s*=/g) || []).length, 1);
  assert.match(source, /data-flyout-link="home"/);
  assert.match(source, /data-flyout-link="tutorial"/);
  assert.match(source, /data-flyout-link="game"/);
  assert.match(source, /data-action="copy-invite" data-game-id=/);
  assert.doesNotMatch(source, /replaceWith\(previousBoardPanel\)/);
});

test("live sync applies authoritative pushed game payloads before render", () => {
  assert.match(source, /payload\?\.type === "state_sync"/);
  assert.match(source, /payload\?\.type === "event_appended"/);
  assert.match(source, /transport\.applyLiveGameUpdate\(\{ game: payload\.game, eventSeq: payload\.eventSeq, clientCommandId: payload\.clientCommandId \?\? null \}\);/);
  assert.match(source, /if \(document\.getElementById\("shell-header-last-event"\)\) \{\s*updateHeaderFields\(\);\s*\} else \{\s*render\(\{ animatePanels: false, includeBoard: false \}\);\s*\}/s);
});

test("live sync status renders are deduplicated by stable status key", () => {
  assert.match(source, /let lastWsStatusKey = toStableKey\(wsStatus\);/);
  assert.match(source, /const statusKey = toStableKey\(status\);/);
  assert.match(source, /if \(statusKey === lastWsStatusKey\) \{\s*return;\s*\}/s);
  assert.match(source, /lastWsStatusKey = statusKey;\s*wsStatus = status;\s*if \(status\.state === "closed" && status\.reconnectAttempts >= 3\) \{\s*void syncRouteDataPassive\(\);\s*\}[\s\S]*updateHeaderFields\(\);/s);
});

test("syncLiveChannels manages subscriptions through the shared active game set", () => {
  assert.match(
    source,
    /const activeLiveGameIds = new Set\(\);/,
  );
  assert.match(source, /const desiredGameIds = new Set\(routeGameId \? \[routeGameId\] : getHomeActiveGameIds\(\)\);/);
  assert.match(source, /liveSync\.disconnectGame\(gameId\);/);
  assert.match(source, /liveSync\.connectGame\(gameId\);/);
});

test("history renderer emits move-only rows without visible turn wrappers", () => {
  assert.doesNotMatch(source, /class="history-turn"/);
  assert.doesNotMatch(source, /class="history-turn-header"/);
  assert.doesNotMatch(source, /class="history-turn-list"/);
  assert.match(source, /const getControlSeatForTurn = \(state, turnOwnerSeat\) => \{/);
  assert.match(source, /if \(continuation\.type === "push" && continuation\.phase === "retreat"\) \{\s*return getNextSeat\(turnOwnerSeat\);/s);
  assert.match(source, /const moveRows = game\.turns\.flatMap/);
  assert.match(source, /const pendingRows = \(Array\.isArray\(game\.pendingMoves\) \? game\.pendingMoves : \[\]\)\.map/);
  assert.match(source, /const reverseChronologicalMoveRows = \[\.\.\.moveRows\]\.reverse\(\);/);
  assert.match(source, /const reverseChronologicalPendingRows = \[\.\.\.pendingRows\]\.reverse\(\);/);
  assert.match(source, /const branchButton = game\.inHistoryMode && game\.historyIndex === move\.index/);
  assert.match(source, /class="history-item history-item-pending/);
  assert.match(source, /Pending<\/span>/);
  assert.match(source, /const liveContinuationText =[\s\S]*Live: Waiting for \$\{controlSeat \|\| "next player"\} to continue\.\.\./s);
  assert.match(source, /const liveWaitingText =[\s\S]*Live: Waiting on \$\{activeTurn\.playerSeat \|\| "next player"\} to move\.\.\./s);
  assert.match(source, /const liveStatusText = liveContinuationText \?\? liveWaitingText;/);
  assert.match(source, /class="history-item history-item-waiting history-empty-line/);
  assert.match(source, /return `\$\{reverseChronologicalPendingRows\.join\(""\)\}\$\{reverseChronologicalMoveRows\.join\(""\)\}`;/);
  assert.doesNotMatch(source, /if \(game\.inHistoryMode && activeTurn\.moveIndexes\.length > 0\) \{/);
  assert.match(source, /if \(!game\.inHistoryMode && !liveStatusItem && activeTurn\.moveIndexes\.length > 0\) \{\s*return `\$\{reverseChronologicalPendingRows\.join\(""\)\}\$\{reverseChronologicalMoveRows\.join\(""\)\}`;\s*\}/s);
  assert.match(source, /history-empty-line history-return-live"><button class="secondary" data-action="return-live"/);
  assert.match(source, /return `\$\{emptyTurnItem\}\$\{reverseChronologicalPendingRows\.join\(""\)\}\$\{reverseChronologicalMoveRows\.join\(""\)\}`;/);
  assert.match(source, /const hasHistoryMoves = Array\.isArray\(game\.moves\) && game\.moves\.length > 0;/);
  assert.match(source, /data-action="launch-history-branch"/);
  assert.match(source, /Create new game at this move/);
  assert.match(source, /Incoming live moves will appear at top\./);
  assert.match(source, /: hasHistoryMoves\s*\? '<p class="small">You are on the live view\.<\/p><p class="small">Click moves below to see historical state\.<\/p>'\s*: '<p class="small">You are on the live view\.<\/p>'/);
});

test("transport subscriptions drive immediate game-shell updates", () => {
  assert.match(source, /transport\.subscribe\(\(change\) => \{\s*render\(\{\s*animatePanels: false,\s*includeBoard: change\?\.type !== "optimistic_enqueue",\s*\}\);\s*\}\);/s);
  assert.match(source, /const shouldUseIncrementalGameShell = \(gameId = currentRoute\.gameId\) => \{/);
  assert.match(source, /return !getActiveApprovalRequest\(game\) && doesMountedFlyoutStateMatchRoute\(\);/);
  assert.match(source, /if \(currentRoute\.name === "game"\) \{\s*if \(shouldUseIncrementalGameShell\(\)\) \{\s*updateMountedGameShell\(\{/s);
});

test("scenario selector labels use titles without visible ids", () => {
  assert.match(source, /`\$\{scenario\.title\}\$\{scenario\.incorrect \? " \[incorrect\]" : ""\}`/);
  assert.doesNotMatch(source, /`\$\{scenario\.id\} - \$\{scenario\.title\}/);
  assert.match(source, /scenarioId:\s*crypto\.randomUUID\(\),/);
  assert.doesNotMatch(source, /window\.prompt\("Scenario title:", "Saved scenario"\)/);
  assert.match(source, /data-scenario-editable="title"/);
  assert.match(source, /data-scenario-editable="description"/);
  assert.match(source, /contenteditable="plaintext-only" role="textbox" aria-label="Scenario title"/);
  assert.match(source, /contenteditable="plaintext-only" role="textbox" aria-label="Scenario description"/);
  assert.match(source, /data-action="update-scenario"/);
  assert.match(source, /data-scenario-save-field="title"/);
  assert.match(source, /data-scenario-save-field="description"/);
  assert.match(source, /Load a scenario/);
  assert.match(source, /Create a scenario/);
  assert.match(source, /Update to match current board/);
  assert.match(source, /Save current board as new scenario/);
  assert.match(source, /canAuthorScenariosLocally\(\)/);
  assert.match(source, /const canSaveScenario = canAuthorScenarios && Boolean\(saveDraft\.title && saveDraft\.description\);/);
  assert.match(source, /const title = getScenarioEditableFieldText\("title"\);/);
  assert.match(source, /const description = getScenarioEditableFieldText\("description"\);/);
  assert.match(source, /appEl\.addEventListener\("focusout", \(event\) => \{/);
  assert.match(source, /target\.hasAttribute\("data-scenario-editable"\)/);
  assert.match(source, /window\.setTimeout\(async \(\) => \{/);
  assert.match(source, /includeCurrentBoard:\s*false,/);
  assert.match(source, /Scenario \$\{scenario\.id\} details saved\./);
  assert.doesNotMatch(source, /downloadScenarioCatalog/);
});

test("debug flyout persists locally while scenario-created games close the scenarios flyout", () => {
  assert.match(source, /import \{ loadDebugFlyoutOpen, saveDebugFlyoutOpen, saveTutorialCompleted \} from "\.\/persistence\.js";/);
  assert.match(source, /const getPersistedDebugFlyoutOpen = \(\) => loadDebugFlyoutOpen\(storage\);/);
  assert.match(source, /const routeWithPersistedPreferences = \{\s*\.\.\.route,\s*debug: getPersistedDebugFlyoutOpen\(\),\s*\};/s);
  assert.match(source, /return \{\s*\.\.\.routeWithPersistedPreferences,\s*\.\.\.resolveFlyoutState\(routeWithPersistedPreferences,/s);
  assert.doesNotMatch(source, /toggleDebugHash/);
  assert.match(source, /if \(action === "open-debug"\) \{[\s\S]*saveDebugFlyoutOpen\(storage, true\);[\s\S]*currentRoute = normalizeRouteFlyoutState\(\{ \.\.\.currentRoute, debug: true \}, \{ preferredFlyoutKey: "debug" \}\);[\s\S]*render\(\);/s);
  assert.match(source, /if \(action === "close-debug"\) \{[\s\S]*saveDebugFlyoutOpen\(storage, false\);[\s\S]*currentRoute = normalizeRouteFlyoutState\(\{ \.\.\.currentRoute, debug: false \}\);[\s\S]*render\(\);/s);
  assert.match(source, /if \(action === "close-scenarios"\) \{[\s\S]*navigateTo\(toggleScenariosHash\(window\.location\.hash\)\);[\s\S]*\}/s);
  assert.match(source, /const nextHash = buildGameHash\(result\.game\.id, null, \{\s*\.\.\.getCurrentFlyoutState\(\),\s*scenarios: false,\s*\}\);/s);
});

test("history branch launch keeps the source tab stable while opening a new tab", () => {
  assert.match(source, /action !== "jump-history" &&[\s\S]*action !== "launch-history-branch" &&[\s\S]*action !== "return-live"/s);
  assert.match(source, /if \(action === "launch-history-branch"\) \{[\s\S]*buildHistoryBranchSeedFromGame\(activeGame, moveIndex\);[\s\S]*transport\.launchHistoryBranch\(/s);
  assert.match(source, /window\.open\(`\$\{window\.location\.pathname\}\$\{window\.location\.search\}\$\{nextHash\}`,\s*"_blank",\s*"noopener"\);/);
  assert.match(source, /const initialSelectionAction = !game\.inHistoryMode \? game\.initialSelectionAction \?\? null : null;/);
  assert.match(source, /const hydratedSelectionAction = scenarioSelectionHydration\.selectionAction \?\? initialSelectionAction;/);
  assert.match(source, /selectionAction: hydratedSelectionAction,/);
});

test("history navigation skips the busy pre-render but still clears disabled state after completion", () => {
  assert.match(source, /const shouldRenderBusyStateStart =\s*action !== "copy-invite" &&[\s\S]*action !== "jump-history" &&[\s\S]*action !== "launch-history-branch" &&[\s\S]*action !== "return-live"/s);
  assert.match(source, /const shouldRenderBusyStateEnd =\s*action !== "copy-invite" &&[\s\S]*action !== "tutorial-next" &&[\s\S]*action !== "tutorial-skip" &&[\s\S]*action !== "open-debug" &&[\s\S]*action !== "open-scenarios" &&[\s\S]*action !== "close-debug" &&[\s\S]*action !== "close-scenarios";/s);
  assert.match(source, /\}, \{ renderStart: shouldRenderBusyStateStart, renderEnd: shouldRenderBusyStateEnd \}\);/);
});

test("shell renders and reconciles mini board previews for home and debug surfaces", () => {
  assert.match(source, /const miniBoardPreviewRegistry = new Map\(\);/);
  assert.match(source, /const renderedMiniBoardPreviewPayloads = new Map\(\);/);
  assert.match(source, /const renderMiniBoardPreviewRoot = \(\{ previewId, snapshot, selection = null, previewKey, sizeVariant = "compact" \}\) => \{/);
  assert.match(source, /data-mini-board-preview data-preview-id=/);
  assert.match(source, /const reconcileMiniBoardPreviews = \(\) => \{/);
  assert.match(source, /syncMiniBoardPreviews\(\{/);
  assert.match(source, /const getGamePreviewSnapshot = \(game\) => game\?\.liveCurrentSnapshot \?\? game\?\.board\?\.state \?\? game\?\.currentSnapshot \?\? null;/);
  assert.match(source, /previewId: `home:\$\{game\.id\}`/);
  assert.match(source, /previewId: `scenario:\$\{selectedScenario\.id\}`/);
  assert.match(source, /class="mini-board-card"/);
  assert.match(source, /class="mini-board-card-link-surface"[\s\S]*href=/);
  assert.match(source, /data-game-id="\$\{escapeHtml\(game\.id\)\}"/);
  assert.match(source, /As of \$\{escapeHtml\(formatClientDateTime\(game\.lastMoveAt \|\| game\.createdAt\)\)\}/);
  assert.match(source, /const recoveryChip = game\.syncStatus === "desynced" \? '<span class="status-chip">Recovering<\/span>' : "";/);
  assert.match(source, /const isDualSeatIdentity = \(game\) =>/);
  assert.match(source, /return '<strong class="player-tone-both">both players<\/strong>';/);
  assert.match(source, /const renderConnectionStatusIcon = \(status, label\) =>/);
  assert.match(source, /const getMyConnectionMessage = \(game\) =>/);
  assert.match(source, /game\?\.myConnectionConnected \? "You are connected here" : "You are not connected here"/);
  assert.match(source, /const renderPlayerSlotStatus = \(seat, participant, \{ verbose = false \} = \{\}\) =>/);
  assert.match(source, /return `<span class="mini-board-card-connection-item">\$\{renderSeatLabel\(seat\)\}\$\{renderConnectionStatusIcon\(\s*"open",\s*statusLabel,\s*\)\}<\/span>`;/s);
  assert.match(source, /const shouldUseVerboseHomeConnectionCopy = \(game\) =>/);
  assert.match(source, /const renderHomeRoleLine = \(game\) =>/);
  assert.doesNotMatch(source, /renderConnectionStatusIcon\(Boolean\(game\?\.myConnectionConnected\),/);
  assert.match(source, /if \(game\?\.myRole === "Guest"\) \{\s*return game\?\.canJoinAsPlayer \? "Open to join as player" : "Open to view";\s*\}/);
  assert.match(source, /const renderHomeClientConnectionLine = \(game\) =>/);
  assert.match(source, /renderConnectionStatusIcon\(\s*Boolean\(game\?\.myConnectionConnected\) \? "connected" : "disconnected",\s*getMyConnectionMessage\(game\),\s*\)/s);
  assert.match(source, /<span>\$\{escapeHtml\(getMyConnectionMessage\(game\)\)\}<\/span>/);
  assert.match(source, /const myConnectionLine = renderHomeClientConnectionLine\(game\);/);
  assert.match(source, /const renderHomeSeatConnectionLine = \(game\) =>/);
  assert.match(source, /return `<p class="small mini-board-card-connection-line">\$\{connectionSummary\}<\/p>`;/);
  assert.match(source, /return '<p class="small mini-board-card-connection-line is-placeholder" aria-hidden="true"><span>&nbsp;<\/span><\/p>';/);
  assert.match(source, /const seatConnectionLine = renderHomeSeatConnectionLine\(game\);/);
  assert.match(source, /const cardInfoLines = \[myConnectionLine, seatConnectionLine\]/);
  assert.match(source, /const renderHomeConnectionSummary = \(game\) =>/);
  assert.match(source, /const filteredSlots = isDualSeatIdentity\(game\) && isPlayerRole\(game\?\.myRole\)/);
  assert.match(source, /renderPlayerSlotStatus\(entry\.seat, entry\.participant, \{ verbose: shouldUseVerboseHomeConnectionCopy\(game\) \}\)/);
  assert.match(source, /<div class="mini-board-card-copy">/);
  assert.match(source, /<div class="mini-board-card-meta mini-board-card-meta-primary">/);
  assert.match(source, /<span>\$\{renderHomeRoleLine\(game\)\}<\/span>/);
  assert.match(source, /\$\{cardInfoLines\}/);
  assert.match(source, /const moveLabel = Array\.isArray\(game\.moves\) \? `Move \$\{game\.moves\.length \+ 1\}` : "Move pending";/);
  assert.match(source, /reconcileMiniBoardPreviews\(\);\s*scheduleGameShellStickyLayout\(\);/);
});

test("withBusy only repaints immediately for actions that need visible busy state", () => {
  assert.match(source, /const withBusy = async \(fn, \{ renderStart = true, renderEnd = true \} = \{\}\) => \{/);
  assert.match(source, /if \(renderStart\) \{\s*render\(\);\s*\}/s);
  assert.match(source, /const shouldRenderBusyStateStart =\s*action !== "copy-invite" &&[\s\S]*action !== "jump-history" &&[\s\S]*action !== "launch-history-branch" &&[\s\S]*action !== "return-live" &&[\s\S]*action !== "tutorial-next" &&[\s\S]*action !== "tutorial-skip" &&[\s\S]*action !== "open-debug" &&[\s\S]*action !== "open-scenarios" &&[\s\S]*action !== "close-debug" &&[\s\S]*action !== "close-scenarios";/s);
  assert.match(source, /const shouldRenderBusyStateEnd =\s*action !== "copy-invite" &&[\s\S]*action !== "tutorial-next" &&[\s\S]*action !== "tutorial-skip" &&[\s\S]*action !== "open-debug" &&[\s\S]*action !== "open-scenarios" &&[\s\S]*action !== "close-debug" &&[\s\S]*action !== "close-scenarios";/s);
  assert.match(source, /\}, \{ renderStart: shouldRenderBusyStateStart, renderEnd: shouldRenderBusyStateEnd \}\);/);
  assert.match(source, /const renderFeedbackReveal = \(message\) =>/);
  assert.match(source, /feedback-reveal\$\{message \? " is-visible" : ""\}/);
  assert.match(source, /const setInviteFeedback = \(message\) => \{\s*inviteFeedback = message;\s*render\(\{ animatePanels: false, includeBoard: false \}\);/s);
});

test("scenario flyout alone forces click target selection on hover-capable boards", () => {
  assert.match(source, /const forceClickTargetSelection = currentRoute\.scenarios;/);
  assert.match(source, /selectionState: scenarioSelectionHydration\.selectionState,[\s\S]*forceClickTargetSelection,[\s\S]*\}\);/s);
  assert.match(source, /getForceClickTargetSelection: \(\) => forceClickTargetSelection,/);
});

test("history navigation uses pointer-down press state with a single mouseup release bounce", () => {
  assert.match(source, /const startHistoryPress = \(actionEl\) => \{/);
  assert.match(source, /const startControlPress = \(controlEl\) => \{/);
  assert.match(source, /const clearHistoryPress = \(\) => \{/);
  assert.match(source, /const clearControlPress = \(\) => \{/);
  assert.match(source, /const playHistoryReleaseBounce = \(actionEl\) => \{/);
  assert.match(source, /const playControlReleaseBounce = \(controlEl\) => \{/);
  assert.match(source, /boardWrapEl\.classList\.add\("history-board-pressing"\);/);
  assert.match(source, /boardWrapEl\.classList\.add\("history-board-release"\);/);
  assert.match(source, /actionEl\.classList\.add\("history-item-release"\);/);
  assert.match(source, /appEl\.addEventListener\("pointerdown", \(event\) => \{[\s\S]*const controlEl = target\.closest\("button, \.button-link, \.mini-board-card-link-surface"\);[\s\S]*startControlPress\(controlEl\);/s);
  assert.match(source, /window\.addEventListener\("pointerup", \(event\) => \{[\s\S]*action === "jump-history" \|\| action === "return-live"[\s\S]*return;[\s\S]*clearHistoryPress\(\);\s*\}\);/s);
  assert.match(source, /appEl\.addEventListener\("pointerdown", \(event\) => \{[\s\S]*action !== "jump-history" && action !== "return-live"[\s\S]*startHistoryPress\(actionEl\);/s);
  assert.match(source, /const animateHistoryDeselection = async \(actionEl\) => \{/);
  assert.match(source, /currentSelected\.classList\.add\("is-deselecting"\);/);
  assert.match(source, /if \(action === "jump-history"\) \{[\s\S]*clearControlPress\(\);[\s\S]*clearHistoryPress\(\);[\s\S]*playHistoryReleaseBounce\(actionEl\);[\s\S]*await animateHistoryDeselection\(actionEl\);/s);
  assert.match(source, /if \(action === "return-live"\) \{[\s\S]*clearHistoryPress\(\);[\s\S]*playHistoryReleaseBounce\(actionEl\);/s);
});
