import {mkdir,writeFile,cp,readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {publicRun,hash} from './model.mjs';
const assets=fileURLToPath(new URL('./assets/',import.meta.url));
export async function renderReport(run,dir){
 await mkdir(dir,{recursive:true});await cp(assets,dir,{recursive:true});
 const data=publicRun(run);
 for(const stage of data.stages) for(const item of stage.items){item.revision??=hash({result:item.status,assertions:item.assertions,images:item.images,findings:item.findings});}
 const json=JSON.stringify(data).replaceAll('<','\\u003c');
 await writeFile(path.join(dir,'index.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex"><title>Validation evidence</title><link rel="stylesheet" href="style.css"></head><body><main><header><p class="eyebrow">RIGHELT · VALIDATION</p><h1>Evidence & review</h1><p id="identity"></p></header><section id="summary" class="summary"><h2>TL;DR</h2></section><section id="prs"></section><section class="toolbar" aria-label="Review tools"><label>Review status <select id="filter"><option value="all">All</option></select></label><label>Order <select id="sort"><option value="planned">Planned merge order</option><option value="status">Review status</option></select></label><button id="expand">Expand all</button><button id="collapse">Collapse all</button><button id="export">Export review</button><label class="button">Import review<input id="import" type="file" accept="application/json" hidden></label></section><p id="counts" aria-live="polite"></p><p class="muted">Your review is saved in this browser only. Export/import transfers it between devices. Completing review does not approve or merge a PR.</p><p id="storage-warning" role="alert"></p><section id="conflicts" aria-live="polite"></section><div id="stages"></div></main><dialog id="viewer" aria-label="Screenshot viewer"><div class="viewer-tools"><button id="close">Close</button><button id="previous">Previous</button><button id="next">Next</button><button id="fit">Fit</button><button id="actual">Actual size</button><button id="minus" aria-label="Zoom out">−</button><button id="plus" aria-label="Zoom in">+</button><span id="caption"></span></div><div id="image-scroll"><img id="full-image" alt=""></div></dialog><script id="report-data" type="application/json">${json}</script><script type="module" src="app.mjs"></script></body></html>`);
 await writeFile(path.join(dir,'_headers'),'/*\n  X-Robots-Tag: noindex\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: no-referrer\n');
}
